
version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    labels:
        POSTGRES_USER: ${PGUSERNAME}
        POSTGRES_PASSWORD: ${PGPASSWORD}
    # environment:
    #   - POSTGRES_USER=postgres
    #   - POSTGRES_PASSWORD=p@sSw0rD
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
  app:
    container_name: wt_app
    build:
      context: ./ 
    image: wt_app
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - 8080:8080
    # environment:
    #   HOST: 0.0.0.0
    #   HOST_URL: http://40.88.12.242:8080
    #   COOKIE_ENCRYPT_PWD: superAwesomePasswordStringThatIsAtLeast32CharactersLong!
    #   NODE_ENV: development
      
    #   OKTA_ORG_URL: https://dev-59598263.okta.com
    #   OKTA_CLIENT_ID: 0oa58me7658dghC7K5d7
    #   OKTA_CLIENT_SECRET: yGO-hInM2mbqWBjMiaFq0PVsUdJbwBJeraucqgci
      
    #   PGHOST: db
    #   PGUSERNAME: pgadmin
    #   PGDATABASE: postgres
    #   PGPASSWORD: p@sSw0rD
    #   PGPORT: 5432
    links:
      - db
    volumes:
      - './:/src'
volumes:
  db:
    driver: local